### ISSUE TITLE
[S1 - PBI9] Admin bisa mendaftarkan Travel Agen

### ISSUE THREAD

**Issue by Nayaaa** [SI-RPL-2022/SI4308_A_LANJALAN#10]
Admin bisa mendaftarkan akun travel agent yang baru saja bermitra

**Comment by Nazharr** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92198633/165422153-775a83cc-c3b9-4239-9ae6-389d13d88905.png">
