### ISSUE TITLE
[S2 - PBI23] User bisa melihat daftar wisata

### ISSUE THREAD

**Issue by karismanabil** [SI-RPL-2022/SI4308_A_LANJALAN#21]
Disini user sudah dapat melihat daftar wisata

**Comment by diandralutfi** [comment]
![image](https://user-images.githubusercontent.com/92174534/165709502-11d8a963-a3d0-4cef-8219-5e079d7fef0a.png)

**Comment by diandralutfi** [comment]
![image](https://user-images.githubusercontent.com/92174534/165710172-e83d396a-ca17-4719-9ec2-0d479623d9bd.png)

**Comment by diandralutfi** [comment]
Referensi user untuk melihat daftar wisata
