### ISSUE TITLE
[S2 - PBI26] User bisa melihat daftar Travel Agent

### ISSUE THREAD

**Issue by diandralutfi** [SI-RPL-2022/SI4308_A_LANJALAN#22]
Pada Issue ini user dapat melihat daftar-daftar dari travel agent

**Comment by karismanabil** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/65218932/165710772-60d74c7c-08bf-45e0-bd62-6cca6b66ab6f.png">

ini buat referensi daftar travel agent
