### ISSUE TITLE
[S2- PBI27] User bisa melihat daftar paket bundling

### ISSUE THREAD

**Issue by Nazharr** [SI-RPL-2022/SI4308_A_LANJALAN#24]
Saya sebagai user ingin melihat daftar paket bundling yang tersedia

**Comment by karismanabil** [comment]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/65218932/165719610-ad984c59-2252-493e-bc74-4b9a22399026.png">

referensi paket bundling
