### ISSUE TITLE
[S1 - PBI5] Admin bisa melihat detail wisata

### ISSUE THREAD

**Issue by diandralutfi** [SI-RPL-2022/SI4308_A_LANJALAN#5]

**Comment by karismanabil** [comment]
![image](https://user-images.githubusercontent.com/65218932/164234460-5272031f-46d0-467c-81aa-58d526a46d3d.png)

**Comment by diandralutfi** [comment]
![detail_wisata](https://user-images.githubusercontent.com/92174534/164360982-6c5ef70c-c8f3-4c03-a7fb-150c9db9337b.png)
